import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import "leaflet/dist/leaflet.css";
import { Poppins, Karla } from "next/font/google";

export const karla = Karla({
  weight: ["700", "400", "500"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-karla",
});

export const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

export const metadata = {
  title: "M.Hassan Gulzar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${karla.variable} ${poppins.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
